// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfzafchqpdxmqawjffyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmemFmY2hxcGR4bXFhd2pmZnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDA0MTIsImV4cCI6MjA1MTY3NjQxMn0.QxAyj7-79hGsCLTAS1yrNI9CNddruut6VZmKKQY1f9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);